---
- name: Install Helm
  community.general.snap:
    name: helm
    classic: true

- name: Add falcosecurity chart repo
  kubernetes.core.helm_repository:
    name: falcosecurity
    repo_url: "https://falcosecurity.github.io/charts"

- name: Get Falco values.yaml config
  ansible.builtin.copy:
    src: ./deps/values-agent.yaml
    dest: "/home/{{ microk8s_user }}/values.yaml"
    mode: "0644"
    owner: "{{ microk8s_user }}"
    group: "{{ microk8s_user }}"

- name: Install Falco via Helm
  kubernetes.core.helm:
    update_repo_cache: true
    name: falco
    chart_ref: falcosecurity/falco
    release_namespace: falco
    create_namespace: true
    set_values:
      - value: tty=true
    values_files:
      - "/home/{{ microk8s_user }}/values.yaml"
    values:
      falco:
        http_output:
          url: "http://{{ telemetry_hostname }}:2801/"
    kubeconfig: "/home/{{ microk8s_user }}/.kube/config"
    state: present
 

- name: Configure k8s audit pipeline for Falco
  block:
    - name: Install k8saudit collector
      kubernetes.core.helm:
        update_repo_cache: true
        name: k8s-metacollector
        chart_ref: falcosecurity/k8s-metacollector
        release_namespace: falco
        create_namespace: true
        kubeconfig: "/home/{{ microk8s_user }}/.kube/config"
        state: present

    - name: Get k8saudit webhook cluster IP
      ansible.builtin.command:
        cmd: >
          microk8s kubectl get svc falco-k8saudit-webhook
          -n falco
          -o jsonpath='{.spec.clusterIP}'
      register: webhookIP
      changed_when: false

    - name: Get k8saudit webhook port
      ansible.builtin.command:
        cmd: >
          microk8s kubectl get svc falco-k8saudit-webhook
          -n falco
          -o jsonpath='{.spec.ports[0].port}'
      register: webhookPort
      changed_when: false

    - name: Get webhook config
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/heilancoos/k8s-custom-detections/refs/heads/main/lab-setup/webhook-config.yaml"
        dest: "{{ microk8s_base }}/current/args/webhook-config.yaml"

    - name: Get audit policy
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/heilancoos/k8s-custom-detections/refs/heads/main/lab-setup/audit-policy.yaml"
        dest: "{{ microk8s_base }}/current/args/audit-policy.yaml"

    - name: Update webhook URL in webhook config
      ansible.builtin.lineinfile:
        path: "{{ microk8s_base }}/current/args/webhook-config.yaml"
        regexp: 'server: http://.*:.*\/k8s-audit'
        line: "    server: http://{{ webhookIP.stdout }}:{{ webhookPort.stdout }}/k8s-audit"

    - name: Add audit log path to API server
      ansible.builtin.lineinfile:
        path: "{{ microk8s_apiserver }}"
        line: "--audit-log-path={{ microk8s_base }}/common/var/log/kube-apiserver-audit.log"
        create: true

    - name: Add audit webhook file path to API server
      ansible.builtin.lineinfile:
        path: "{{ microk8s_apiserver }}"
        line: "--audit-webhook-config-file={{ microk8s_base }}/current/args/webhook-config.yaml"
        create: true

    - name: Add audit policy file path to API server
      ansible.builtin.lineinfile:
        path: "{{ microk8s_apiserver }}"
        line: "--audit-policy-file={{ microk8s_base }}/current/args/audit-policy.yaml"
        create: true

    - name: Restart MicroK8s API server
      ansible.builtin.systemd_service:
        name: snap.microk8s.daemon-kubelite.service
        daemon_reload: true
        state: restarted

