- name: Install Docker
  block:
    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
    - name: add GPG key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
    - name: Add Docker repo
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Install Docker
      ansible.builtin.apt:
        pkg: 
          - docker.io
          - docker-compose-plugin
        state: latest
        update_cache: true
    - name: add user to docker group
      ansible.builtin.user:
        user: "{{ telemetry_user }}"
        group: docker
- name: Install falcosidekick-ui
  block:
    - name: Copy docker-compose file 
      ansible.builtin.copy:
        src: ./deps/docker-compose.yml
        dest: "/home/{{ telemetry_user }}/docker-compose.yml"
        mode: "0644"
        owner: "{{ telemetry_user }}"
        group: "{{ telemetry_user }}"
    - name: Run docker-compose
      community.docker.docker_compose_v2:
        project_src: "/home/{{ telemetry_user }}"
      register: output
