---
- name: "Falco agent on this node"
  ansible.builtin.include_tasks: falco-agent.yml

- name: "Configure Grafana/Loki on this node"
  ansible.builtin.include_tasks: grafana.yml
  when: ui == 'grafana'

- name: "Deploy Falcosidekick with built-in web UI"
  ansible.builtin.include_tasks: falco-ui.yml
  when: ui == 'falcosidekick'


