---
- name: "Falco agent on this node"
  ansible.builtin.include_tasks: falco-agent.yml
  when:
    - telemetry_role in ['agent', 'full']

- name: "Falco Sidekick UI on this node"
  ansible.builtin.include_tasks: falco-ui.yml
  when:
    - telemetry_role in ['ui', 'full']

- name: "Configure Grafana/Loki on this node"
  ansible.builtin.include_tasks: grafana.yml
  when:
    - ui == 'grafana'
    - telemetry_role in ['agent', 'full']

- name: "Run attack chain execution steps"
  ansible.builtin.include_tasks: attack_chain_exec.yml
  when: enable_attack_chain is true

- name: "Install custom Helm charts"
  ansible.builtin.include_tasks: install_helm_chart.yml
  when: install_helm_chart | default([]) | length > 0



