- name: Install Helm
  community.general.snap:
    name: helm
    classic: true
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: falcosecurity
    repo_url: "https://falcosecurity.github.io/charts"
- name: Get values.yaml config
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/heilancoos/k8s-custom-detections/refs/heads/main/lab-setup/values.yaml"
    dest: "/home/{{ microk8s_user }}/values.yaml"
- name: Installing Falco via Helm
  kubernetes.core.helm:
    update_repo_cache: true
    name: falcosecurity
    chart_ref: falcosecurity/falco
    release_namespace: falco
    create_namespace: true
    values_files:
      - "/home/{{ microk8s_user }}/values.yaml"
    kubeconfig: "/home/{{ microk8s_user }}/.kube/config"
- name: Configuring K8saudit
  block:
    - name: Installing k8saudit
      kubernetes.core.helm:
        name: k8s-metacollector
        chart_ref: falcosecurity/k8s-metacollector
        release_namespace: falco
        kubeconfig: "/home/{{ microk8s_user }}/.kube/config"
    - name: Setting webhook ip variable
      ansible.builtin.command: microk8s kubectl get svc falcosecurity-k8saudit-webhook -n falco -o jsonpath='{.spec.clusterIP}'
      register: webhookIP
    - name: Setting webhook port variable
      ansible.builtin.command: microk8s kubectl get svc falcosecurity-k8saudit-webhook -n falco -o jsonpath='{.spec.ports[0].port}'
      register: webhookPort
    - name: Get webhook config
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/heilancoos/k8s-custom-detections/refs/heads/main/lab-setup/webhook-config.yaml"
        dest: "{{ microk8s_base }}/current/args/webhook-config.yaml"
    - name: Get audit policy
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/heilancoos/k8s-custom-detections/refs/heads/main/lab-setup/audit-policy.yaml"
        dest: "{{ microk8s_base }}/current/args/audit-policy.yaml"
    - name: Modify webhook config
      ansible.builtin.lineinfile:
        path: "{{ microk8s_base }}/current/args/webhook-config.yaml"
        regexp: 'server: http://.*:.*\/k8s-audit'
        line: "    server: http://{{ webhookIP.stdout }}:{{ webhookPort.stdout }}/k8s-audit"
    - name: Add audit log path to API Server
      ansible.builtin.lineinfile:
        path: "{{ microk8s_apiserver }}"
        line: "--audit-log-path={{ microk8s_base }}/common/var/log/kube-apiserver-audit.log"
        create: yes
    - name: Add audit webhook file path to API Server
      ansible.builtin.lineinfile:
        path: "{{ microk8s_apiserver }}"
        line: "--udit-webhook-config-file={{ microk8s_base }}/current/args/webhook-config.yaml"
        create: yes
    - name: Add audit policy file path to API Server
      ansible.builtin.lineinfile:
        path: "{{ microk8s_apiserver }}"
        line: "--audit-policy-file={{ microk8s_base }}/current/args/audit-policy.yaml"
        create: yes
    - name: Restart API Server
      ansible.builtin.systemd_service:
        name: snap.microk8s.daemon-kubelite.service
        daemon_reload: true
        state: restarted
    



