---
- name: Install microk8s
  community.general.snap:
    name: microk8s
    classic: true
- name: Create a microk8s user
  ansible.builtin.user:
    name: "{{ microk8s_user }}"
    groups: microk8s
    append: true

- name: Adding node to cluster
  ansible.builtin.include_tasks: multinode.yml
  when: multinode is true

- name: Cluster Configruation
  block:
#    - name: Disable ha-cluster
#      ansible.builtin.command:
#        cmd: microk8s disable ha-cluster --force
 #     ignore_errors: true
    - name: Wait for microk8s to be ready
      ansible.builtin.command:
        cmd: microk8s status --wait-ready
      ignore_errors: true
    - name: Enable plugins
      ansible.builtin.command:
        cmd: "microk8s enable {{ item }}"
      loop: "{{ microk8s_addons }}"
      ignore_errors: true
    - name: Ensure kube config directory exists
      ansible.builtin.file:
        path: "/home/{{ microk8s_user }}/.kube"
        state: directory
        owner: "{{ microk8s_user }}"
        group: "{{ microk8s_user }}"
        mode: "0700"
    - name: Modify API Server
      ansible.builtin.lineinfile:
        path: "{{ microk8s_apiserver }}"
        regexp: '^--authorization-mode='
        line: '--authorization-mode=Node,RBAC'
    - name: Create KubeConfig
      ansible.builtin.shell: "microk8s config > /home/{{ microk8s_user }}/.kube/config"
    - name: Add kubectl alias
      ansible.builtin.lineinfile:
        path: "/home/{{ microk8s_user }}/.bashrc"
        line: "alias kubectl='microk8s kubectl'"
        create: yes
    - name: Restart API Server
      ansible.builtin.systemd_service:
        name: snap.microk8s.daemon-kubelite.service
        daemon_reload: true
        state: restarted
  

