---
- name: Wait for snapd to be ready
  ansible.builtin.command:
    cmd: snap wait system seed.loaded
  changed_when: false
  
- name: Install microk8s
  ansible.builtin.command:
    cmd: >
      snap install microk8s --classic
      {{ ('--channel=' + microk8s_version) if microk8s_version | default('') else '' }}
    creates: /snap/bin/microk8s

- name: Update repositories cache and install podman package
  ansible.builtin.apt:
    name: podman
    update_cache: yes
  
- name: Create a microk8s user
  ansible.builtin.user:
    name: "{{ k8s_user }}"
    groups: microk8s
    append: true
- name: Reset SSH connection so group membership applies
  ansible.builtin.meta: reset_connection
- name: Adding node to cluster
  ansible.builtin.include_tasks: multinode.yml
  when: multinode is true

- name: Cluster Configruation
  block:
    - name: Disable ha-cluster
      ansible.builtin.command:
        cmd: microk8s disable ha-cluster --force
      when: not multinode
      ignore_errors: true
    - name: Wait for microk8s to be ready
      ansible.builtin.command:
        cmd: microk8s status --wait-ready
      ignore_errors: true
    - name: Enable plugins
      ansible.builtin.command:
        cmd: "microk8s enable {{ item }}"
      loop: "{{ microk8s_addons }}"
      ignore_errors: true
    - name: Ensure kube config directory exists
      ansible.builtin.file:
        path: "/home/{{ k8s_user }}/.kube"
        state: directory
        owner: "{{ k8s_user }}"
        group: "{{ k8s_user }}"
        mode: "0700"
    # - name: Modify API Server
    #   ansible.builtin.lineinfile:
    #     path: "{{ microk8s_apiserver }}"
    #     regexp: '^--authorization-mode='
    #     line: '--authorization-mode=Node,RBAC'
    - name: Create KubeConfig
      ansible.builtin.shell: "microk8s config > /home/{{ k8s_user }}/.kube/config"
    - name: Add kubectl alias
      ansible.builtin.lineinfile:
        path: "/home/{{ k8s_user }}/.bashrc"
        line: "alias kubectl='microk8s kubectl'"
        create: yes
    - name: Restart API Server
      ansible.builtin.systemd_service:
        name: snap.microk8s.daemon-kubelite.service
        daemon_reload: true
        state: restarted


- name: Install kubernetes Python library
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present

- name: Install Helm
  ansible.builtin.command:
    cmd: snap install helm --channel=3.7/stable --classic
    creates: /snap/bin/helm

- name: Create a rules directory
  ansible.builtin.file:
    path: "/home/{{ k8s_user }}/rules.d"
    state: directory
    mode: '0755'
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user }}"

