- name: Install kubernetes Python library
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present

- name: Create a pod with writable pod_hostpath
  kubernetes.core.k8s:
    kubeconfig: "/home/{{ microk8s_user }}/.kube/config"
    name: pod_hostpath
    state: present
    namespace: default
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: pod-hostpath
      spec:
        containers:
          - name: test
            image: nginx
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: hostpath-vol
                mountPath: /mnt/hostpath
        volumes:
          - name: hostpath-vol
            hostPath:
              path: /tmp/hostpath
              type: DirectoryOrCreate


- name: Get Rules
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/heilancoos/k8s-custom-detections/refs/heads/main/falco/rules/volumemounts-rules.yaml"
    dest: "/home/{{ microk8s_user }}/rules.d"