- name: Configure unauth API
  block:
    - name: Modify API Server Config
      ansible.builtin.lineinfile:
        path: /var/snap/microk8s/current/args/kube-apiserver
        regexp: '^--anonymous-auth='
        line: '--anonymous-auth=true'
    - name: Modify Kubelet API Config
      ansible.builtin.lineinfile:
        path: /var/snap/microk8s/current/args/kubelet
        regexp: '^--anonymous-auth='
        line: '--anonymous-auth=true'
    - name: Restart APIs 
      ansible.builtin.systemd_service:
        name: snap.microk8s.daemon-kubelite.service
        state: restarted
    - name: Install Kubeletctl
      ansible.builtin.get_url:
        url: "https://github.com/cyberark/kubeletctl/releases/download/{{ kubeletctl_version }}/kubeletctl_linux_amd64"
        dest: "{{ kubeletctl_install_path }}"
        mode: '0755'

- name: Get Anon Rules
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/heilancoos/k8s-custom-detections/refs/heads/main/falco/rules/anonymous-auth-apis.yaml"
    dest: "/home/{{ microk8s_user }}/rules.d/"